import api from '../config/api';

// Helper to simulate AI delay and return mock data if backend fails
const mockCall = async (mockData, delay = 1000) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      // Add isMock flag to array or object results if possible
      if (Array.isArray(mockData)) {
        // Can't easily attach property to array without breaking structure, 
        // so consumers should check if the data matches mock data or handle it elsewhere.
        // For objects, we can attach it.
        resolve(mockData);
      } else if (typeof mockData === 'object' && mockData !== null) {
        resolve({ ...mockData, isMock: true });
      } else {
        resolve(mockData);
      }
    }, delay);
  });
};

// Get glossary terms and definitions
export const getGlossaryTerms = async (content) => {
  if (!content || content.trim().length === 0) return [];

  try {
    const { data } = await api.post('/ai/glossary', { content });
    return Array.isArray(data) ? data : [];
  } catch (error) {
    console.warn('AI Service Error (Glossary):', error.message);
    return mockCall([
      { term: 'React', definition: 'A JavaScript library for building user interfaces.' },
      { term: 'Component', definition: 'Independent and reusable bits of code.' },
      { term: 'State', definition: 'An object that determines how that component renders & behaves.' }
    ]);
  }
};

// Generate summary
export const generateSummary = async (content) => {
  if (!content || content.trim().length === 0) return '';
  const mockSummary = 'This is a simulated summary of your note. The backend appears to be offline, so this placeholder text is shown to demonstrate the UI layout. In a real scenario, this would be a concise overview of your content generated by the AI.';

  try {
    const { data } = await api.post('/ai/summary', { content });
    return data?.summary || '';
  } catch (error) {
    console.warn('AI Service Error (Summary):', error.message);
    return mockCall(mockSummary);
  }
};

// Generate tags
export const generateTags = async (content) => {
  if (!content || content.trim().length === 0) return [];
  const mockTags = ['Productivity', 'Ideas', 'Planning', 'Draft', 'Important'];

  try {
    const { data } = await api.post('/ai/tags', { content });
    return Array.isArray(data) ? data.slice(0, 5) : [];
  } catch (error) {
    console.warn('AI Service Error (Tags):', error.message);
    return mockCall(mockTags);
  }
};

// Check grammar
export const checkGrammar = async (content) => {
  if (!content || content.trim().length === 0) return [];
  const mockGrammar = [
    { text: 'teh', suggestion: 'the' },
    { text: 'recieve', suggestion: 'receive' }
  ];

  try {
    const { data } = await api.post('/ai/grammar', { content });
    return Array.isArray(data) ? data : [];
  } catch (error) {
    console.warn('AI Service Error (Grammar):', error.message);
    return mockCall(mockGrammar);
  }
};

// Extract Action Items (New)
export const extractActionItems = async (content) => {
  if (!content || content.trim().length === 0) return [];
  const mockActions = ['Review this note', 'Follow up on key points'];

  try {
    const { data } = await api.post('/ai/actions', { content });
    return Array.isArray(data) ? data : [];
  } catch (error) {
    console.warn('AI Service Error (Actions):', error.message);
    // Simple regex fallback for demo purposes
    const regex = /TODO:|Action:|\[ \]/gi;
    if (regex.test(content)) {
      return mockCall(['Review project requirements', 'Email the team', 'Schedule meeting']);
    }
    return mockCall(mockActions);
  }
};

// Analyze Sentiment (New)
export const analyzeSentiment = async (content) => {
  if (!content || content.trim().length === 0) return 'Neutral';
  const mockSentiment = 'Positive';

  try {
    const { data } = await api.post('/ai/sentiment', { content });
    return data?.sentiment || 'Neutral';
  } catch (error) {
    console.warn('AI Service Error (Sentiment):', error.message);
    return mockCall(mockSentiment);
  }
};

// Generate Quiz (New)
export const generateQuiz = async (params) => {
  const mockQuiz = {
    title: `Quiz: ${params.topic}`,
    questions: [
      {
        question: 'What is the primary function of this topic?',
        options: ['Function A', 'Function B', 'Function C', 'Function D'],
        correctAnswer: 0,
        hint: 'Consider the main purpose.'
      },
      {
        question: 'Which key concept relates to this?',
        options: ['Concept X', 'Concept Y', 'Concept Z', 'Concept W'],
        correctAnswer: 1,
        hint: 'It is fundamental to the theory.'
      }
    ]
  };

  try {
    const { data } = await api.post('/ai/quiz/generate', params);
    return data || mockCall(mockQuiz, 2000);
  } catch (error) {
    console.warn('AI Service Error (Quiz):', error.message);
    return mockCall(mockQuiz, 2000);
  }
};

// Get Quiz Hint (New)
export const getQuizHint = async (question, subject) => {
  const mockHint = 'Review the fundamental definitions of this topic.';

  try {
    const { data } = await api.post('/ai/quiz/hint', { question, subject });
    return data?.hint || mockHint;
  } catch (error) {
    console.warn('AI Service Error (Hint):', error.message);
    return mockCall(mockHint);
  }
};

// Chat with Note (New)
export const chatWithNote = async (content, query) => {
  if (!content || !query) return '';
  const mockChat = `I analyzed your note. You asked: "${query}". Here is a simulated response based on the context of your note. The AI suggests focusing on the key objectives mentioned in the second paragraph.`;

  try {
    const { data } = await api.post('/ai/chat', { content, query });
    return data?.response || '';
  } catch (error) {
    console.warn('AI Service Error (Chat):', error.message);
    return mockCall(mockChat);
  }
};

